import type { Profile, Project } from '@/types';

export function isDemoMode() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
  return process.env.NEXT_PUBLIC_DEMO_MODE === 'true' || !url || url.includes('placeholder.supabase.co');
}

const now = new Date().toISOString();

export const demoProfiles = {
  investor: {
    id: 'demo-investor',
    email: 'demo.inversor@suelo.ai',
    full_name: 'Demo Inversor',
    role: 'investor',
    phone: '+595 981 000 000',
    dni: null,
    company_name: null,
    avatar_url: null,
    kyc_verified: true,
    total_invested: 4200,
    total_returns: 386,
    created_at: now,
    updated_at: now,
  } satisfies Profile,
  developer: {
    id: 'demo-developer',
    email: 'demo.developer@suelo.ai',
    full_name: 'Demo Desarrollador',
    role: 'developer',
    phone: '+591 700 000 00',
    dni: null,
    company_name: 'Constructora Demo PY/BO',
    avatar_url: null,
    kyc_verified: true,
    total_invested: 0,
    total_returns: 0,
    created_at: now,
    updated_at: now,
  } satisfies Profile,
  admin: {
    id: 'demo-admin',
    email: 'demo.admin@suelo.ai',
    full_name: 'Demo Admin',
    role: 'admin',
    phone: null,
    dni: null,
    company_name: 'Suelo Operaciones',
    avatar_url: null,
    kyc_verified: true,
    total_invested: 0,
    total_returns: 0,
    created_at: now,
    updated_at: now,
  } satisfies Profile,
} as const;

export const demoProjects: Project[] = [
  {
    id: 'demo-asuncion-eje',
    developer_id: demoProfiles.developer.id,
    title: 'Torre Asunción Eje',
    slug: 'torre-asuncion-eje',
    description: 'Edificio mixto con unidades residenciales y locales comerciales en zona corporativa de Asunción. Foco en renta y plusvalía.',
    location: 'Asunción, Paraguay',
    address: 'Eje corporativo, Asunción',
    latitude: null,
    longitude: null,
    status: 'funding',
    total_value: 1800000,
    token_price: 100,
    total_tokens: 18000,
    sold_tokens: 12960,
    min_investment: 100,
    expected_return: 14.2,
    return_period_months: 21,
    start_date: null,
    end_date: null,
    image_url: null,
    gallery_urls: [],
    documents_url: null,
    featured: true,
    created_at: now,
    updated_at: now,
    developer: demoProfiles.developer,
  },
  {
    id: 'demo-santa-cruz-lofts',
    developer_id: demoProfiles.developer.id,
    title: 'Santa Cruz Business Lofts',
    slug: 'santa-cruz-business-lofts',
    description: 'Lofts para alquiler ejecutivo en Santa Cruz con flujo mensual proyectado y documentación de obra organizada.',
    location: 'Santa Cruz, Bolivia',
    address: 'Equipetrol, Santa Cruz',
    latitude: null,
    longitude: null,
    status: 'in_progress',
    total_value: 920000,
    token_price: 100,
    total_tokens: 9200,
    sold_tokens: 5336,
    min_investment: 100,
    expected_return: 10.8,
    return_period_months: 12,
    start_date: null,
    end_date: null,
    image_url: null,
    gallery_urls: [],
    documents_url: null,
    featured: true,
    created_at: now,
    updated_at: now,
    developer: demoProfiles.developer,
  },
  {
    id: 'demo-la-paz-altura',
    developer_id: demoProfiles.developer.id,
    title: 'Residencias La Paz Altura',
    slug: 'residencias-la-paz-altura',
    description: 'Residencias en preventa con ticket accesible, avance por hitos y salida por venta de unidades.',
    location: 'La Paz, Bolivia',
    address: 'Zona Sur, La Paz',
    latitude: null,
    longitude: null,
    status: 'funding',
    total_value: 640000,
    token_price: 250,
    total_tokens: 2560,
    sold_tokens: 1100,
    min_investment: 250,
    expected_return: 12.6,
    return_period_months: 18,
    start_date: null,
    end_date: null,
    image_url: null,
    gallery_urls: [],
    documents_url: null,
    featured: false,
    created_at: now,
    updated_at: now,
    developer: demoProfiles.developer,
  },
];

export const demoInvestments = [
  { id: 'inv-1', investor_id: demoProfiles.investor.id, project_id: demoProjects[0].id, tokens_purchased: 18, amount: 1800, status: 'confirmed', created_at: now, project: demoProjects[0] },
  { id: 'inv-2', investor_id: demoProfiles.investor.id, project_id: demoProjects[1].id, tokens_purchased: 14, amount: 1400, status: 'confirmed', created_at: now, project: demoProjects[1] },
  { id: 'inv-3', investor_id: demoProfiles.investor.id, project_id: demoProjects[2].id, tokens_purchased: 4, amount: 1000, status: 'pending', created_at: now, project: demoProjects[2] },
];

export const demoTransactions = [
  { id: 'tx-1', type: 'investment', amount: 1800, created_at: now, project: { title: demoProjects[0].title } },
  { id: 'tx-2', type: 'investment', amount: 1400, created_at: now, project: { title: demoProjects[1].title } },
  { id: 'tx-3', type: 'return', amount: 126, created_at: now, project: { title: demoProjects[1].title } },
];

export const demoDeveloperInvestments = [
  { id: 'dev-inv-1', investor_id: 'lead-1', tokens_purchased: 18, amount: 1800, created_at: now, investor: { full_name: 'María Alvarenga', email: 'maria@example.com' } },
  { id: 'dev-inv-2', investor_id: 'lead-2', tokens_purchased: 30, amount: 3000, created_at: now, investor: { full_name: 'Ramiro Torres', email: 'ramiro@example.com' } },
  { id: 'dev-inv-3', investor_id: 'lead-3', tokens_purchased: 12, amount: 1200, created_at: now, investor: { full_name: 'Carla Méndez', email: 'carla@example.com' } },
];
